# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRlX-tJX8szt7je52browFdx8IHSk8wP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# 1. UPLOAD DATASET
print("Please upload your CSV file:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

# --- EXPLORATORY ANALYSIS ---
print("\n--- Exploratory Analysis ---")
# Visualizing correlation between study time, attendance, and final grade (G3)
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix of Student Factors")
plt.show()

# --- UNSUPERVISED CLUSTERING (K-Means) ---
# We use studytime, attendance, and failures to identify patterns
X_clustering = df[['studytime', 'attendance', 'failures']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_clustering)

# Applying K-Means (let's assume 3 profiles: High, Medium, Low performers)
kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_transform(X_scaled).argmax(axis=1)

# Labeling Clusters based on means
# Note: You may need to inspect cluster means to ensure labels match the data
cluster_map = {0: 'Irregular Learners', 1: 'Average Learners', 2: 'Consistent Learners'}
df['Learning_Profile'] = df['Cluster'].map(cluster_map)

print("\nCluster Distribution:")
print(df['Learning_Profile'].value_counts())

# --- SUPERVISED LEARNING ---
# Task: Predict whether a student will Pass (G3 >= 10) or Fail (G3 < 10)
df['Pass'] = (df['G3'] >= 10).astype(int)

# Features (Past grades G1, G2, and student patterns)
X = df[['studytime', 'attendance', 'absences', 'G1', 'G2', 'failures']]
y = df['Pass']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 1. Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
lr_cv = cross_val_score(log_reg, X, y, cv=5)

# 2. Random Forest
rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train, y_train)
rf_cv = cross_val_score(rf_clf, X, y, cv=5)

# --- EVALUATION ---
print("\n--- Model Performance ---")
print(f"Logistic Regression CV Accuracy: {lr_cv.mean():.2f}")
print(f"Random Forest CV Accuracy: {rf_cv.mean():.2f}")

print("\nRandom Forest Detailed Report:")
y_pred = rf_clf.predict(X_test)
print(classification_report(y_test, y_pred))